
-- description generated by Pat driver

--			date     : Mon Dec  8 22:55:43 2025
--			revision : v109

--			sequence : default

-- input / output list :
out      ko_p B;;;
in       vdd B;;;
in       vss B;;;
in       ck B;;;
in       nreset B;;;
in       arg_p (7 downto 0) X;;;
in       rok_arg_p B;;;
in       wok_res_p B;;;
signal   wr_arg B;;;
signal   argd (7 downto 0) X;;;
signal   rd_arg B;;;
signal   rd_res B;;;
signal   res (7 downto 0) X;;;
signal   wr_res B;;;
register data.pt (7 downto 0) X;;
register data.opa B;;
register data.opb B;;
register data.res B;;
register data.stop B;;
signal   data.lastpt B;;
register core.read_opa B;;
register core.read_opb B;;
register core.compare B;;
register core.decr_a B;;
register core.decr_b B;;

begin

-- Pattern description :

--                         k  v  v  c  n  a   r  w   w   a    r   r   r    w   d   d  d  d  d  d  c  c  c  c  c  
--                         o  d  s  k  r  r   o  o   r   r    d   d   e    r   a   a  a  a  a  a  o  o  o  o  o  
--                         _  d  s     e  g   k  k   _   g    _   _   s    _   t   t  t  t  t  t  r  r  r  r  r  
--                         p           s  _   _  _   a   d    a   r        r   a   a  a  a  a  a  e  e  e  e  e  
--                                     e  p   a  r   r        r   e        e   .   .  .  .  .  .  .  .  .  .  .  
--                                     t      r  e   g        g   s        s   p   o  o  r  s  l  r  r  c  d  d  
--                                            g  s                             t   p  p  e  t  a  e  e  o  e  e  
--                                            _  _                                 a  b  s  o  s  a  a  m  c  c  
--                                            p  p                                          p  t  d  d  p  r  r  
--                                                                                             p  _  _  a  _  _  
--                                                                                             t  o  o  r  a  b  
--                                                                                                p  p  e        
--                                                                                                a  b           


-- Beware : unprocessed patterns

<          0 ps>        : ?*  1  0  0  0  00  0  0  ?*  ?**  ?*  ?*  ?**  ?*  ?** ?* ?* ?* ?* ?* ?* ?* ?* ?* ?* ;
<          1 ps>        : ?*  1  0  0  0  78  1  0  ?*  ?**  ?*  ?*  ?**  ?*  ?** ?* ?* ?* ?* ?* ?* ?* ?* ?* ?* ;
<          2 ps>        : ?*  1  0  0  1  78  1  0  ?*  ?**  ?*  ?*  ?**  ?*  ?** ?* ?* ?* ?* ?* ?* ?* ?* ?* ?* ;
<          3 ps>        : ?*  1  0  0  1  10  1  0  ?*  ?**  ?*  ?*  ?**  ?*  ?** ?* ?* ?* ?* ?* ?* ?* ?* ?* ?* ;
<          5 ps>        : ?*  1  0  0  1  08  0  0  ?*  ?**  ?*  ?*  ?**  ?*  ?** ?* ?* ?* ?* ?* ?* ?* ?* ?* ?* ;
<         11 ps>        : ?*  1  0  0  1  08  0  1  ?*  ?**  ?*  ?*  ?**  ?*  ?** ?* ?* ?* ?* ?* ?* ?* ?* ?* ?* ;
<         13 ps>        : ?*  1  0  0  1  40  1  0  ?*  ?**  ?*  ?*  ?**  ?*  ?** ?* ?* ?* ?* ?* ?* ?* ?* ?* ?* ;
<         15 ps>        : ?*  1  0  0  1  11  1  0  ?*  ?**  ?*  ?*  ?**  ?*  ?** ?* ?* ?* ?* ?* ?* ?* ?* ?* ?* ;
<         17 ps>        : ?*  1  0  0  1  01  0  0  ?*  ?**  ?*  ?*  ?**  ?*  ?** ?* ?* ?* ?* ?* ?* ?* ?* ?* ?* ;

end;
