convert:
	vasy -I vhd -v cordic_top
# 	yosys -c yosys.tcl
clean:
	rm cordic_top.blif \
	rm cordic_top.spi \
	rm cordic_top.v \
	rm cordic_top.vst \
	rm cordic_top.ys \
	rm -rf __pycache__/* \
	rm .doit.db \
	rm chip.spi \
	rm chip.vst \
	rm cordic_top_cts_r.gds \
	rm cordic_top_cts_r.spi \
	rm cordic_top_cts_r.vst \
	rm corona.spi \
	rm corona.vst \
	rm .vslrun \