convert:
	vasy -I vhd -v cordic_cor_opt
# 	yosys -c yosys.tcl
clean:
	rm cordic_cor_opt.blif \
	rm cordic_cor_opt.spi \
	rm cordic_cor_opt.v \
	rm cordic_cor_opt.vst \
	rm cordic_cor_opt.ys \
	rm -rf __pycache__/* \
	rm .doit.db \
	rm chip.spi \
	rm chip.vst \
	rm cordic_cor_opt_cts_r.gds \
	rm cordic_cor_opt_cts_r.spi \
	rm cordic_cor_opt_cts_r.vst \
	rm corona.spi \
	rm corona.vst \
	rm .vslrun \