convert:
	vasy -I vhd -v cordic_cor
# 	yosys -c yosys.tcl
clean:
	rm cordic_cor.blif \
	rm cordic_cor.spi \
	rm cordic_cor.v \
	rm cordic_cor.vst \
	rm cordic_cor.ys \
	rm -rf __pycache__/* \
	rm .doit.db \
	rm chip.spi \
	rm chip.vst \
	rm cordic_cor_cts_r.gds \
	rm cordic_cor_cts_r.spi \
	rm cordic_cor_cts_r.vst \
	rm corona.spi \
	rm corona.vst \
	rm .vslrun \